"""Ports (protocols) — implemented by infrastructure adapters.

Use these to keep the application layer free of framework dependencies.
"""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from coach_api.domain.entities import Coach, Court, Player, Season, WeeklyPlan


class CoachRepository(Protocol):
    async def list_all(self) -> list[Coach]: ...
    async def get(self, coach_id: UUID) -> Coach | None: ...
    async def upsert(self, coach: Coach) -> Coach: ...


class PlayerRepository(Protocol):
    async def list_all(self) -> list[Player]: ...
    async def get(self, player_id: UUID) -> Player | None: ...
    async def upsert(self, player: Player) -> Player: ...


class CourtRepository(Protocol):
    async def list_all(self) -> list[Court]: ...
    async def upsert(self, court: Court) -> Court: ...


class SeasonRepository(Protocol):
    async def list_all(self) -> list[Season]: ...
    async def get(self, season_id: UUID) -> Season | None: ...
    async def create(self, season: Season) -> Season: ...


class PlanRepository(Protocol):
    async def list_for_season(self, season_id: UUID) -> list[WeeklyPlan]: ...
    async def get(self, plan_id: UUID) -> WeeklyPlan | None: ...
    async def save_many(self, plans: list[WeeklyPlan]) -> list[WeeklyPlan]: ...
